"""initial schema

Revision ID: a60b6b25fd16
Revises: 
Create Date: 2026-04-29 12:43:51.344656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a60b6b25fd16'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cultivation_units',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('legacy_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legacy_id')
    )
    op.create_table('fish_traceability_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('fish_id', sa.BigInteger(), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('event_time', sa.TIMESTAMP(), nullable=False),
    sa.Column('source_table', sa.String(length=80), nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pond_types',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('legacy_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legacy_id')
    )
    op.create_table('roles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('legacy_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('resource_type', sa.String(length=120), nullable=True),
    sa.Column('resource_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legacy_id')
    )
    op.create_table('species',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('legacy_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('internal_id', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legacy_id')
    )
    op.create_table('transports',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('legacy_id', sa.BigInteger(), nullable=True),
    sa.Column('sheet_number', sa.Integer(), nullable=True),
    sa.Column('delivery_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('chofer', sa.String(length=120), nullable=True),
    sa.Column('phone_number', sa.BigInteger(), nullable=True),
    sa.Column('license_plate', sa.String(length=40), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legacy_id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('legacy_id', sa.BigInteger(), nullable=True),
    sa.Column('email', sa.String(length=190), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('lastname', sa.String(length=120), nullable=True),
    sa.Column('rut', sa.String(length=30), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('legacy_id')
    )
    op.create_table('lots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('legacy_id', sa.BigInteger(), nullable=True),
    sa.Column('species_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('internal_id', sa.String(length=120), nullable=True),
    sa.Column('origin', sa.String(length=120), nullable=True),
    sa.Column('hatch_year', sa.Integer(), nullable=True),
    sa.Column('creation_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('creation_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('national', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legacy_id')
    )
    op.create_table('mortality_reports',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('legacy_id', sa.BigInteger(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('registry_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('breeding_user_id', sa.BigInteger(), nullable=True),
    sa.Column('supervisor_user_id', sa.BigInteger(), nullable=True),
    sa.Column('general_user_id', sa.BigInteger(), nullable=True),
    sa.Column('supervisor_validation', sa.Boolean(), nullable=True),
    sa.Column('general_validation', sa.Boolean(), nullable=True),
    sa.Column('supervisor_validation_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('general_validation_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['breeding_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['general_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supervisor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legacy_id')
    )
    op.create_table('users_roles',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('fish',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('legacy_id', sa.BigInteger(), nullable=True),
    sa.Column('internal_id', sa.String(length=120), nullable=False),
    sa.Column('lot_id', sa.BigInteger(), nullable=False),
    sa.Column('sex', sa.String(length=20), nullable=True),
    sa.Column('state', sa.String(length=30), nullable=True),
    sa.Column('registration_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('devious_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('date_of_death', sa.TIMESTAMP(), nullable=True),
    sa.Column('depuration_start_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('mortality_id', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legacy_id')
    )
    op.create_table('ponds',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('legacy_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('internal_id', sa.String(length=120), nullable=True),
    sa.Column('code', sa.String(length=120), nullable=True),
    sa.Column('cultivation_unit_id', sa.BigInteger(), nullable=True),
    sa.Column('pond_type_id', sa.BigInteger(), nullable=True),
    sa.Column('lot_id', sa.BigInteger(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('depuration', sa.Boolean(), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('biomass', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('avg_weight', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['cultivation_unit_id'], ['cultivation_units.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.ForeignKeyConstraint(['pond_type_id'], ['pond_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legacy_id')
    )
    op.create_table('depuration_periodic_samplings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('legacy_id', sa.BigInteger(), nullable=True),
    sa.Column('fish_id', sa.BigInteger(), nullable=True),
    sa.Column('pond_id', sa.BigInteger(), nullable=True),
    sa.Column('development_state', sa.String(length=80), nullable=True),
    sa.Column('width', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('heigh', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('weight', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('harvest_date', sa.Date(), nullable=True),
    sa.Column('color', sa.String(length=80), nullable=True),
    sa.Column('gonad_dimension', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('oocyte_size', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('flavor', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['fish_id'], ['fish.id'], ),
    sa.ForeignKeyConstraint(['pond_id'], ['ponds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legacy_id')
    )
    op.create_table('fish_female_samplings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('legacy_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('fish_id', sa.BigInteger(), nullable=False),
    sa.Column('length', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('weight', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('oocyte_size', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('color', sa.String(length=80), nullable=True),
    sa.Column('gonad_size', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('flavor', sa.String(length=80), nullable=True),
    sa.Column('development_state', sa.String(length=80), nullable=True),
    sa.Column('harvest_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('registry_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('diameter', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('agglomeration', sa.Integer(), nullable=True),
    sa.Column('turgor', sa.Integer(), nullable=True),
    sa.Column('fat', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['fish_id'], ['fish.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legacy_id')
    )
    op.create_table('ponds_movements',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('legacy_id', sa.BigInteger(), nullable=True),
    sa.Column('source_pond_id', sa.BigInteger(), nullable=True),
    sa.Column('destiny_pond_id', sa.BigInteger(), nullable=True),
    sa.Column('fish_id', sa.BigInteger(), nullable=True),
    sa.Column('lot_id', sa.BigInteger(), nullable=True),
    sa.Column('fish_quantity', sa.Integer(), nullable=False),
    sa.Column('movement_reason', sa.String(length=50), nullable=False),
    sa.Column('movement_time', sa.TIMESTAMP(), nullable=False),
    sa.Column('folio', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['destiny_pond_id'], ['ponds.id'], ),
    sa.ForeignKeyConstraint(['fish_id'], ['fish.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.ForeignKeyConstraint(['source_pond_id'], ['ponds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legacy_id')
    )
    op.create_table('marked_mortality_registries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('legacy_id', sa.BigInteger(), nullable=True),
    sa.Column('mortality_report_id', sa.BigInteger(), nullable=False),
    sa.Column('ponds_movement_id', sa.BigInteger(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('registry_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('supervisor_validation', sa.Boolean(), nullable=True),
    sa.Column('general_validation', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['mortality_report_id'], ['mortality_reports.id'], ),
    sa.ForeignKeyConstraint(['ponds_movement_id'], ['ponds_movements.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legacy_id')
    )
    op.create_table('unmarked_mortality_registries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('legacy_id', sa.BigInteger(), nullable=True),
    sa.Column('mortality_report_id', sa.BigInteger(), nullable=False),
    sa.Column('ponds_movement_id', sa.BigInteger(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('registry_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('supervisor_validation', sa.Boolean(), nullable=True),
    sa.Column('general_validation', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['mortality_report_id'], ['mortality_reports.id'], ),
    sa.ForeignKeyConstraint(['ponds_movement_id'], ['ponds_movements.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legacy_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unmarked_mortality_registries')
    op.drop_table('marked_mortality_registries')
    op.drop_table('ponds_movements')
    op.drop_table('fish_female_samplings')
    op.drop_table('depuration_periodic_samplings')
    op.drop_table('ponds')
    op.drop_table('fish')
    op.drop_table('users_roles')
    op.drop_table('mortality_reports')
    op.drop_table('lots')
    op.drop_table('users')
    op.drop_table('transports')
    op.drop_table('species')
    op.drop_table('roles')
    op.drop_table('pond_types')
    op.drop_table('fish_traceability_events')
    op.drop_table('cultivation_units')
    # ### end Alembic commands ###
